name: E2E

on:
  pull_request:
    branches: [main]
    paths:
      - examples/react/** 

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./examples/react
        run: pnpm install

      - name: Install Playwright Browsers
        working-directory: ./examples/react
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: ./examples/react
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: examples/react/playwright-report/
          retention-days: 2
