name: CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check build
        run: pnpm -r build

      - name: Check types
        run: pnpm -r typecheck

      - name: Check format
        run: pnpm format

      - name: Run Tests
        run: pnpm -r test
